version: '3'

services:
  http_proxy:
    image: ci-tool-stack/tinyproxy:${VERSION:-latest}
    build:
      context: .
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
    ports:
      - "8888:8888"
    entrypoint: /usr/bin/tinyproxy -d -c /tinyproxy/tinyproxy.conf
    volumes:
      - "./tinyproxy.conf:/tinyproxy/tinyproxy.conf:ro"
#      - "./tinyproxy-log:/var/log/tinyproxy:rw"
