#!/bin/bash
#
#  push image version
# REPOSITORY_URL
# REPOSITORY_USERNAME
# REPOSITORY_PASSWORD
set -e

REGISTRY_URL=${REGISTRY_URL:-nexus}
REGISTRY_USERNAME=${REGISTRY_USERNAME:? REGISTRY_USERNAME not defined }
REGISTRY_PASSWORD=${REGISTRY_PASSWORD:? REGISTRY_PASSWORD not defined}

IMAGE_NAME=${1:? $(basename $0) IMAGE_NAME VERSION needed}
TAG=${2:? $(basename $0) IMAGE_NAME VERSION needed}

docker tag $IMAGE_NAME $REGISTRY_URL/$IMAGE_NAME:$TAG
docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
docker push $REGISTRY_URL/$IMAGE_NAME:$TAG
docker logout $REGISTRY_URL
docker rmi $REGISTRY_URL/$IMAGE_NAME:$TAG


echo $?
